CREATE SEQUENCE SEQ_FLUXOS
    START WITH 1
    INCREMENT BY 1 NOCACHE
    NOCYCLE;

CREATE TABLE TBL_FLUXOS
(
    FLUXOS_ID INTEGER DEFAULT SEQ_FLUXOS.NEXTVAL NOT NULL,
    QTD_VEICULOS    INTEGER NOT NULL,
    V_MEDIA     NUMBER(10,2) NOT NULL
);