name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - develop
      - "feature/**"
  push:
    branches:
      - main
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Unit tests
        run: mvn test