name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main

env:
  IMAGE_NAME: gerenciamento-trafego
  STAGING_WEBAPP_NAME: cidade-inteligente
  PRODUCTION_WEBAPP_NAME: cidade-inteligente

jobs:
  # Build e Teste - Integração Contínua
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  # Deployment para Staging
  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Deploy to Azure Web App (Staging)
        id: deploy-to-webapp-staging
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.STAGING_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PROFILE }}
          images: '${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest'

  # Deployment para Produção
  deploy-production:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Azure Web App (Production)
        id: deploy-to-webapp-production
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.PRODUCTION_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PRODUCTION_WEBAPP_PUBLISH_PROFILE }}
          images: '${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest'
